[package]
name = "terminal_run"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hot-lib-reloader = "^0.6"
terminal = { path = "../terminal" } 
